apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopnow-dev

resources:
  - ns.yaml
  - deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - service.yaml
  # - sealed-secret.yaml