apiVersion: v1
kind: Secret
metadata:
  name: shopnow-fe
  namespace: shopnow-dev
  type: Opaque
stringData:
  REACT_APP_BASE_API_URL: https://api.shopnow-dev.devops4u.online
  REACT_APP_EUREKA_URL: https://api.shopnow-dev.devops4u.online
  REACT_APP_CART_SERVICE_SWAGGER_URL: https://api.shopnow-dev.devops4u.online/swagger-ui/index.html#/
  REACT_APP_USER_SERVICE_SWAGGER_URL: https://api.shopnow-dev.devops4u.online/index.html#/
  REACT_APP_PRODUCT_SERVICE_SWAGGER_URL: https://api.shopnow-dev.devops4u.online/index.html#/