apiVersion: v1
kind: Service
metadata:
  name: shopnow-fe
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: shopnow-fe
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
